project:
  type: website

website:
  title: "Fengruo Zhang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: Bio
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze:auto

